### PR TITLE
Include the Rake::DSL module manually to remove deprecation messages from

### PR DESCRIPTION
**Pull request by ngan**
Include the Rake::DSL module manually to remove deprecation messages from Rake 0.9.2.

### CODE REVIEW

**Comment by dchelimsky** [comment]
Dup of https://github.com/rspec/rspec-core/pull/437, already fixed.

**Comment by ngan** [comment]
I thought rspec-core is for Rspec 2?  We're still on Rspec 1, using rspec-rails 1...

**Comment by dchelimsky** [comment]
You're correct - I didn't notice which repo this was in.

**Comment by ngan** [comment]
Any plans on merging this David?

**Comment by dchelimsky** [comment]
Needs to be wrapped in an `if_defined?(Rake::DSL)` - be glad to merge it if you make that update.

**Comment by ngan** [comment]
Done.

**Pull request merged**
